name: gnome_unit_test

on:
  push:
    branches: [ main, develop, 'release/**', 'hotfix/**', 'feature/**'] 
  pull_request:
    branches: [ main, develop, 'release/**', 'hotfix/**', 'feature/**'] 

env:
  THUNDER_REF: "R4.4.1"

jobs:
  unit-tests:
    name: Build and run unit tests
    runs-on: ubuntu-22.04
        
    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get install -y pkg-config libglib2.0-dev libnm-dev libcurl4-openssl-dev lcov ninja-build

      - name: Configure Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install jsonref

      - name: Configure CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Checkout thunder repositories
        run: |
          git clone https://github.com/rdkcentral/ThunderTools ThunderTools --branch ${{ env.THUNDER_REF }}
          git clone https://github.com/rdkcentral/Thunder Thunder --branch ${{ env.THUNDER_REF }}
          
      - name: Checkout networkmanager
        uses: actions/checkout@v3
        with:
          path: networkmanager
         
      - name: Build ThunderTools
        run: >
          cmake
          -S "${{github.workspace}}/ThunderTools" -B build/ThunderTools
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DGENERIC_CMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          &&
          cmake --build build/ThunderTools --target install -j8

      - name: Build Thunder
        run: >
          cmake
          -S "${{github.workspace}}/Thunder" -B build/Thunder
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DBUILD_TYPE=Debug
          -DBINDING=127.0.0.1
          -DPORT=9998
          &&
          cmake --build build/Thunder --target install -j8
          
      - name: Generate IARM headers
        run: |
            touch install/usr/lib/libIARMBus.so 
            mkdir -p install/usr/include/rdk/iarmbus
            touch install/usr/include/rdk/iarmbus/libIARM.h
            cd "${{github.workspace}}/networkmanager/tests/"
            mkdir -p headers/rdk/iarmbus
            cd headers
            touch rdk/iarmbus/libIARM.h rdk/iarmbus/libIBus.h
            
      - name: Exclude UPnP files
        run: |
          # Path to the CMakeLists.txt file
          CMAKE_FILE="${{github.workspace}}/networkmanager/tests/unittest/CMakeLists.txt"

          # Create a backup of the original file
          cp "$CMAKE_FILE" "$CMAKE_FILE.bak"

          # Print original content for debugging
          echo "Original CMakeLists.txt content:"
          cat "$CMAKE_FILE"

          # Comment out any line containing test_UpnpDiscoveryManager.cpp
          sed -i '/test_UpnpDiscoveryManager\.cpp/ s/^/#/' "$CMAKE_FILE"

          # Comment out any line containing UpnpDiscoveryManager.cpp (in case it's explicitly listed)
          sed -i '/UpnpDiscoveryManager\.cpp/ s/^/#/' "$CMAKE_FILE"

          # Comment out the entire routerDiscovery_tests target block
          sed -i '/add_executable.*routerDiscovery_tests/,/target_link_libraries.*routerDiscovery_tests/ s/^/#/' "$CMAKE_FILE"

          # Print modified content for verification
          echo "Modified CMakeLists.txt content:"
          cat "$CMAKE_FILE"

     

      - name: Build networkmanager with Gnome libnm Proxy
        run: >
          cmake
          -S "${{github.workspace}}/networkmanager"
          -B build/GnomeLibnmNetworkmanager
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DCMAKE_CXX_FLAGS=" -fprofile-arcs -ftest-coverage 
          -I ${{github.workspace}}/networkmanager/tests/headers
          -I ${{github.workspace}}/networkmanager/tests/headers/rdk/iarmbus
          --include ${{github.workspace}}/networkmanager/tests/mocks/Iarm.h
          "
          -DENABLE_GNOME_NETWORKMANAGER=ON
          -DENABLE_PLUGIN_CLI=ON
          -DENABLE_UNIT_TESTING=ON
          -DENABLE_CODE_COVERAGE=ON
          &&
          cmake --build build/GnomeLibnmNetworkmanager --target install -j8

      - name: Build networkmanager with Gnome GDBUS Proxy
        run: >
          cmake
          -S "${{github.workspace}}/networkmanager"
          -B build/GnomeGdbusNetworkmanager
          -DCMAKE_TOOLCHAIN_FILE="${{ env.TOOLCHAIN_FILE }}"
          -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/usr"
          -DCMAKE_MODULE_PATH="${{github.workspace}}/install/tools/cmake"
          -DCMAKE_CXX_FLAGS=" -fprofile-arcs -ftest-coverage "
          -DENABLE_GNOME_NETWORKMANAGER=ON
          -DENABLE_GNOME_GDBUS=ON
          -DENABLE_PLUGIN_CLI=ON
          &&
          cmake --build build/GnomeGdbusNetworkmanager --target install -j8
          
      - name: Run Thunder/WPEFramework
        run: |
          export LD_LIBRARY_PATH=${PWD}/install/usr/lib:${LD_LIBRARY_PATH}
          export PATH=${PWD}/install/usr/bin:${PATH}
          echo "Running Thunder WPEFramework..."
          WPEFramework -f -c ${PWD}/install/etc/WPEFramework/config.json &
          
      - name: Run unit tests for plugin
        run: >
          PATH=${{github.workspace}}/install/usr/bin:${PATH}
          LD_LIBRARY_PATH=${{github.workspace}}/install/usr/lib:${{github.workspace}}/install/usr/lib/wpeframework/plugins:${LD_LIBRARY_PATH}
          l3_tests
         
      - name: Generate coverage
        run: |
            lcov -c -o coverage.info -d build/GnomeLibnmNetworkmanager 
            lcov -r coverage.info '/usr/include/*' '*/build/GnomeLibnmNetworkmanager /*' \
                                  '*/install/usr/include/*' '*/tests/*' 'googlemock/*' 'googletest/*' \
                                  -o filtered_coverage.info
      - name: Generate the html report
        run: |
            genhtml filtered_coverage.info --output-directory /tmp/coverage_report

      - name: Upload the coverage report to Pull request using actions
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: /tmp/coverage_report 


